language: python
python:
  - "2.7"

install:
  - git clone git@github.com:BookBrainz/bookbrainz-schema.git
  - pushd bookbrainz-schema
  - sudo python setup.py install
  - popd
  - pip install -r requirements.txt

script:
  - python test.py
