sudo: false
language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install coveralls coverage
  - pip install -r requirements.txt --use-mirrors
  - pip install https://github.com/BookBrainz/bookbrainz-schema/archive/master.zip

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'CREATE DATABASE bookbrainz_test;' -U postgres
  - psql -c 'CREATE EXTENSION "uuid-ossp"; CREATE SCHEMA musicbrainz;' -d bookbrainz_test -U postgres

script:
  - coverage run --source=bbws test.py

after_success:
  coveralls

notifications:
  email: false
