language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install https://github.com/BookBrainz/bookbrainz-schema/archive/master.zip

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'CREATE DATABASE bookbrainz_test;' -U postgres
  - psql -c 'CREATE EXTENSION "uuid-ossp"; CREATE SCHEMA musicbrainz;' -d bookbrainz_test -U postgres

script:
  - python test.py

notifications:
  email: false
