DEFAULT_MAX_QUANTITY = 100

LANGUAGES_COUNT = 30
GENDERS_COUNT = 30

NEW_ALIASES_MAX_COUNT = 100
NEW_LANGUAGES_MAX_COUNT = 10

GET_BBID_TESTS_GOOD_COUNT = 15
GET_BBID_TESTS_BAD_COUNT = 15

GET_LIST_TESTS_COUNT = 3

POST_TESTS_GOOD_COUNT = 25
POST_TESTS_BAD_COUNT = 0

PUT_TESTS_GOOD_COUNT = 100
PUT_TESTS_BAD_COUNT = 0
