DEFAULT_MAX_QUANTITY = 50

LANGUAGES_COUNT = 30
GENDERS_COUNT = 30

NEW_ALIASES_MAX_COUNT = 20
NEW_LANGUAGES_MAX_COUNT = 20

GET_BBID_TESTS_GOOD_COUNT = 5
GET_BBID_TESTS_BAD_COUNT = 5

GET_LIST_TESTS_COUNT = 3

POST_TESTS_GOOD_COUNT = 5
POST_TESTS_BAD_COUNT = 5

PUT_TESTS_GOOD_COUNT = 5
PUT_TESTS_BAD_COUNT = 5
